version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: uni_pass_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unipass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/internal/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: uni_pass_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
  
  frontend:
    build: ./frontend
    develop:
      watch:
        - action: sync
          path: ./frontend/public
          target: /usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: